name: Terraform AKS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARM_CLIENT_ID: '0993d177-9c02-413f-a737-137e3464c8ab'
  ARM_CLIENT_SECRET: 'Iak8Q~3vF.34Pc7vT.DaLvh8FvMxGajFXLeLccCB'
  ARM_SUBSCRIPTION_ID: '28e1e42a-4438-4c30-9a5f-7d7b488fd883'
  ARM_TENANT_ID: '84f1e4ea-8554-43e1-8709-f0b8589ea118'
  ARM_ACCESS_KEY: '4V0lS3P6tuHrt4L1MdoNtImUCfHWQWggQSx/Zozx6ORwLQf5OtErKxGb+dimJ/L2LU7LPYC+03z++AStSOAakg=='

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
